---
- name: Sleep Playbook
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: do

    - name: sleep
      command: sleep 300

    - name: create file
      file:
        path: "/tmp/foo_{{ tower_job_id }}"
        state: touch
        mode: 0644

    - debug:
        msg: done

